name: deliveroojs

services:
  # ENHSP planner service
  planutils-environment:
    image: maurodep92/unitn_asa_planning-server:enhsp
    ports:
      - "6790:6789"
    restart: unless-stopped

  25c1_1:
    image: maurodep92/unitn_asa_deliveroojs
    ports:
      - "4003:4001"
    restart: unless-stopped

    environment:
      - LEVEL=levels/25c1_1
      - PORT=4001

  25c1_2:
    image: maurodep92/unitn_asa_deliveroojs
    ports:
      - "4004:4001"
    restart: unless-stopped

    environment:
      - LEVEL=levels/25c1_2
      - PORT=4001

  25c1_3:
    image: maurodep92/unitn_asa_deliveroojs
    ports:
      - "4005:4001"
    restart: unless-stopped

    environment:
      - LEVEL=levels/25c1_3
      - PORT=4001

  25c1_4:
    image: maurodep92/unitn_asa_deliveroojs
    ports:
      - "4006:4001"
    restart: unless-stopped

    environment:
      - LEVEL=levels/25c1_4
      - PORT=4001

  25c2_hallway:
    image: maurodep92/unitn_asa_deliveroojs
    ports:
      - "4008:4001"
    restart: unless-stopped

    environment:
      - LEVEL=levels/25c2_hallway
      - PORT=4001